{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "73946183-c5ad-4d64-b05f-084f4ad0e6cf",
   "metadata": {},
   "outputs": [],
   "source": [
    "cnt = int(input('크롤링 할 건수는 몇건입니까?: '))\n",
    "\n",
    "page_cnt = math.ceil(cnt / 10) # 크롤링 할 전체 페이지 수 (올림)\n",
    "print(page_cnt)\n",
    "\n",
    "\n",
    "tit_xpath = '//*[@id=\"search_result\"]/ul/li[*]/div[1]/div[1]/a'\n",
    "no = 0\n",
    "no1 = 0\n",
    "\n",
    "\n",
    "for x in range(1, page_cnt+1):\n",
    "    print(f'========= {x} 페이지 작업 =========')\n",
    "    mylist = driver.find_elements(By.XPATH, tit_xpath)\n",
    "    \n",
    "    for item in mylist:\n",
    "        no += 1\n",
    "        \n",
    "        if no > cnt:\n",
    "            break \n",
    "            \n",
    "        print(no, item.text)\n",
    "        \n",
    "    \n",
    "    if no <= cnt: \n",
    "        if  x == 1 :\n",
    "            a = f'/html/body/div[3]/div/div[1]/div[14]/a[2]'\n",
    "            driver.find_element(By.XPATH, a).click()\n",
    "            time.sleep(2)\n",
    "\n",
    "        elif x == 2 :\n",
    "            a = f'/html/body/div[3]/div/div[1]/div[14]/a[3]'\n",
    "            driver.find_element(By.XPATH, a).click()\n",
    "            time.sleep(2)\n",
    "\n",
    "        elif x == 3 :\n",
    "            a = f'/html/body/div[3]/div/div[1]/div[14]/a[4]'\n",
    "            driver.find_element(By.XPATH, a).click()\n",
    "            time.sleep(2)\n",
    "\n",
    "        elif x == 4 :\n",
    "            a = f'/html/body/div[3]/div/div[1]/div[14]/a[5]'\n",
    "            driver.find_element(By.XPATH, a).click()\n",
    "            time.sleep(2)\n",
    "\n",
    "        elif x == 5 :\n",
    "            a = f'/html/body/div[3]/div/div[1]/div[14]/a[6]'\n",
    "            driver.find_element(By.XPATH, a).click()\n",
    "            time.sleep(2)     \n",
    "        \n",
    "        \n",
    "        elif x == 6 :\n",
    "            a = f'/html/body/div[3]/div/div[1]/div[14]/a[4]'\n",
    "            driver.find_element(By.XPATH, a).click()\n",
    "            time.sleep(2)\n",
    "\n",
    "        elif x == 7 :\n",
    "            a = f'/html/body/div[3]/div/div[1]/div[14]/a[5]'\n",
    "            driver.find_element(By.XPATH, a).click()\n",
    "            time.sleep(2)\n",
    "\n",
    "        elif x == 8 :\n",
    "            a = f'/html/body/div[3]/div/div[1]/div[14]/a[6]'\n",
    "            driver.find_element(By.XPATH, a).click()\n",
    "            time.sleep(2)\n",
    "\n",
    "        elif x == 9 :\n",
    "            a = f'/html/body/div[3]/div/div[1]/div[14]/a[7]'\n",
    "            driver.find_element(By.XPATH, a).click()\n",
    "            time.sleep(2)\n",
    "\n",
    "        elif x == 10 :\n",
    "            a = f'/html/body/div[3]/div/div[1]/div[14]/a[8]'\n",
    "            driver.find_element(By.XPATH, a).click()\n",
    "            time.sleep(2)  \n",
    "        \n",
    "        \n",
    "        elif x > 10 :\n",
    "            if x %6 == 5 :\n",
    "                a = f'/html/body/div[3]/div/div[1]/div[14]/a[4]'\n",
    "                driver.find_element(By.XPATH, a).click()\n",
    "                time.sleep(2)\n",
    "\n",
    "            elif x%7 == 5 :\n",
    "                a = f'/html/body/div[3]/div/div[1]/div[14]/a[5]'\n",
    "                driver.find_element(By.XPATH, a).click()\n",
    "                time.sleep(2)\n",
    "\n",
    "            elif x%8 == 5 :\n",
    "                a = f'/html/body/div[3]/div/div[1]/div[14]/a[6]'\n",
    "                driver.find_element(By.XPATH, a).click()\n",
    "                time.sleep(2)\n",
    "\n",
    "            elif x%9 == 5 :\n",
    "                a = f'/html/body/div[3]/div/div[1]/div[14]/a[7]'\n",
    "                driver.find_element(By.XPATH, a).click()\n",
    "                time.sleep(2)\n",
    "\n",
    "            elif x%10 == 5 :\n",
    "                a = f'/html/body/div[3]/div/div[1]/div[14]/a[8]'\n",
    "                driver.find_element(By.XPATH, a).click()\n",
    "                time.sleep(2)\n",
    "\n",
    "\n",
    "#         next_button = driver.find_element(By.CSS_SELECTOR, f\"a[id='{x+1}']\")\n",
    "#         driver.execute_script(\"arguments[0].click();\", next_button)\n",
    "       \n",
    "\n",
    "        \n",
    "    \n",
    "print('========= 작업 완료 =========')\n",
    "# driver.close()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
